//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by module.rc
//

#pragma once

#define LNG_ENGLISH MAKELANGID(LANG_ENGLISH, SUBLANG_DEFAULT)
#define LNG_RUSSIAN MAKELANGID(LANG_RUSSIAN, SUBLANG_DEFAULT)
#define LNG_POLISH MAKELANGID(LANG_POLISH, SUBLANG_DEFAULT)
#define LNG_CZECH MAKELANGID(LANG_CZECH, SUBLANG_DEFAULT)
#define LNG_UKRAINIAN MAKELANGID(LANG_UKRAINIAN, SUBLANG_DEFAULT)

#pragma region Commands
#define IDC_BTN_OK 1
#define IDC_TITLE 2
#define IDC_VERSION 3
#define IDC_COPYRIGHT 4
#define IDC_LNK_EMAIL 5
#define IDC_LNK_WEB 6
#define IDC_LNK_PATRON 7

#define IDC_BTN_CANCEL 2
#define IDC_BTN_RESET 3
#define IDC_BTN_AUTO 4
#define IDC_CANVAS 5
#define IDC_LBL_HUE 6
#define IDC_TRK_HUE 7
#define IDC_LBL_SAT 8
#define IDC_TRK_SAT 9
#define IDC_RAD_RGB 10
#define IDC_RAD_RED 11
#define IDC_RAD_GREEN 12
#define IDC_RAD_BLUE 13
#define IDC_LBL_IN_LEFT 14
#define IDC_TRK_IN_LEFT 15
#define IDC_LBL_IN_RIGHT 16
#define IDC_TRK_IN_RIGHT 17
#define IDC_LBL_GAMMA 18
#define IDC_TRK_GAMMA 19
#define IDC_LBL_OUT_LEFT 20
#define IDC_TRK_OUT_LEFT 21
#define IDC_LBL_OUT_RIGHT 22
#define IDC_TRK_OUT_RIGHT 23
#pragma endregion

#pragma region Resources
#define IDR_MANIFEST 2
#define IDR_MENU 5

#define IDR_LINEAR_VERTEX 11
#define IDR_LINEAR_FRAGMENT 12
#define IDR_HERMITE_FRAGMENT 13
#define IDR_CUBIC_FRAGMENT 14
#define IDR_LANCZOS_FRAGMENT 15

#define IDR_SCALENX_FRAGMENT_2X 16
#define IDR_SCALENX_FRAGMENT_3X 17

#define IDR_EAGLE_FRAGMENT 18

#define IDR_XSAL_FRAGMENT 19

#define IDR_SCALEHQ_FRAGMENT_2X 20
#define IDR_SCALEHQ_FRAGMENT_4X 21

#define IDR_XBRZ_FRAGMENT_2X 22
#define IDR_XBRZ_FRAGMENT_3X 23
#define IDR_XBRZ_FRAGMENT_4X 24
#define IDR_XBRZ_FRAGMENT_5X 25
#define IDR_XBRZ_FRAGMENT_6X 26
#pragma endregion

#pragma region Dialogs
#define IDD_ABOUT 30
#define IDD_ABOUT_OLD 31
#define IDD_COLOR_ADJUSTMENT 32
#pragma endregion

#pragma region Menu
#define IDM_REND_AUTO 1
#define IDM_REND_GL1 2
#define IDM_REND_GL2 3
#define IDM_REND_GL3 4

#define IDM_VSYNC 7

#define IDM_FPS_OFF 10
#define IDM_FPS_NORMAL 11
#define IDM_FPS_BENCHMARK 12

#define IDM_FILT_OFF 20
#define IDM_FILT_LINEAR 21
#define IDM_FILT_HERMITE 22
#define IDM_FILT_CUBIC 23
#define IDM_FILT_LANCZOS 24

#define IDM_FILT_NONE 25

#define IDM_FILT_SCALENX_2X 26
#define IDM_FILT_SCALENX_3X 27

#define IDM_FILT_EAGLE_2X 28

#define IDM_FILT_XSAL_2X 29

#define IDM_FILT_SCALEHQ_2X 30
#define IDM_FILT_SCALEHQ_4X 31

#define IDM_FILT_XRBZ_2X 32
#define IDM_FILT_XRBZ_3X 33
#define IDM_FILT_XRBZ_4X 34
#define IDM_FILT_XRBZ_5X 35
#define IDM_FILT_XRBZ_6X 36

#define IDM_COLOR_ADJUST 37
#define IDM_ASPECT_RATIO 38
#define IDM_PATCH_CPU 39

#define IDM_MODS 50

#define IDM_HELP_WRAPPER 60

#define IDM_RES_640_480 40005
#define IDM_RES_800_600 40006
#define IDM_RES_1024_768 40007
#define IDM_RES_1280_960 40008
#define IDM_RES_FULL_SCREEN 40009
#define IDM_HELP_MANUAL 40052
#define IDM_HELP_ABOUT 40053

#define IDM_LANG_ENGLISH 1033
#define IDM_LANG_POLISH 1045
#define IDM_LANG_RUSSIAN 1049
#define IDM_LANG_UKRAINIAN 1058
#pragma endregion

#pragma region Strings
#define IDS_ERROR_CHOOSE_PF 1
#define IDS_ERROR_SET_PF 2
#define IDS_ERROR_DESCRIBE_PF 3
#define IDS_ERROR_NEED_PALETTE 4
#define IDS_ERROR_BAD_PF 5
#define IDS_ERROR_ARB_VERSION 6
#define IDS_ERROR_ARB_PROFILE 7
#define IDS_ERROR_LOAD_RESOURCE 8
#define IDS_ERROR_COMPILE_SHADER 9
#define IDS_INFO_RESTART 10

#define IDS_ERROR 11
#define IDS_INFO 12

#define IDS_HOMM_1 13
#define IDS_HOMM_2_SW 14
#define IDS_HOMM_2_POL 15
#define IDS_EDITOR_1 16
#define IDS_EDITOR_2 17
#pragma endregion

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 102
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1004
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
